version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  # Servicio Producer
  producer:
    build:
      context: ./producer
    container_name: producer
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      QUEUE_NAME: email_queue
      PORT: 3000
    depends_on:
      - rabbitmq
    restart: always

  # Servicio Consumer
  consumer:
    build:
      context: ./consumer
    container_name: consumer
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672 
      QUEUE_NAME: email_queue
    depends_on:
      - rabbitmq
    restart: always
volumes:
  rabbitmq_data: