version: '3.8'

services:
  node-app:
    build: .  
    ports:
      - "3000:3000"  
    environment:
      MONGO_URI: "mongodb://mongo-db:27017/bd_agendas" 
    depends_on:
      - mongo-db  
  mongo-db:
    image: mongo:latest  
    container_name: mongo-db
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db 
volumes:
  mongo-data: