version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bd_medico
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - app_network

  nodeapp:
    build: .
    container_name: node_app_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
